language: swift
osx_image: xcode7

script:
- xctool -workspace Tinylog.xcworkspace -scheme Tinylog -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -workspace Tinylog.xcworkspace -scheme TinylogTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i slather --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;
install:
- pod install